env:
  commonjs: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {
  linebreak-style: 0,
  # variables starting with _
  no-underscore-dangle: 0,
  # variables without camelcase naming
  camelcase: 0,
  global-require: 0
}
