# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 1.0$(Rev:.r)

trigger:
- develop

pool:
  vmImage: ubuntu-latest

jobs:
  - job: node
    displayName: Restore and run tests with npm
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - task: WhiteSource@21
      inputs:
        cwd: '$(System.DefaultWorkingDirectory)'
        projectName: 'node-rest-server'

    - script: |
        npm install
        npm run test
      displayName: 'npm install and test'

  - job: publish
    displayName: Publish artifact
    dependsOn: node
    steps:
    # Archive files v2
      # Compress files into .7z, .tar.gz, or .zip.
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: "$(Build.Repository.LocalPath)"
        archiveType: "zip"
        archiveFile: "$(Build.ArtifactStagingDirectory)/drop.zip"
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'